<!-- Global stylesheets -->
<link href="https://fonts.googleapis.com/css?family=Roboto:400,300,100,500,700,900" rel="stylesheet" type="text/css">
<link href="/adminassets/assets/css/icons/icomoon/styles.css" rel="stylesheet" type="text/css">
<link href="/adminassets/assets/css/bootstrap.css" rel="stylesheet" type="text/css">
<link href="/adminassets/assets/css/core.css" rel="stylesheet" type="text/css">
<link href="/adminassets/assets/css/components.css" rel="stylesheet" type="text/css">
<link href="/adminassets/assets/css/colors.css" rel="stylesheet" type="text/css">
<link href="/adminassets/assets/css/custom.css" rel="stylesheet" type="text/css">
<!-- /global stylesheets -->
